pipeline {
  agent any

  environment {
    ACR_NAME = 'cicdacrregistry.azurecr.io'
    IMAGE_NAME = 'flask-app'
  }

  stages {
    stage('Clone Code') {
      steps {
        git 'https://github.com/your-username/ci-cd-project.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $ACR_NAME/$IMAGE_NAME:latest .'
      }
    }

    stage('Login to ACR') {
      steps {
        sh 'az acr login --name cicdacrregistry'
      }
    }

    stage('Push Image') {
      steps {
        sh 'docker push $ACR_NAME/$IMAGE_NAME:latest'
      }
    }

    stage('Deploy to AKS') {
      steps {
        sh 'kubectl apply -f k8s/deployment.yaml'
        sh 'kubectl apply -f k8s/service.yaml'
      }
    }
  }
}
